package org.rokassirvidas.firstlab.mybatis.dao;

import org.mybatis.cdi.Mapper;
import org.rokassirvidas.firstlab.mybatis.model.Branch;

import java.util.List;

@Mapper
public interface BranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BRANCH
     *
     * @mbg.generated Wed Apr 17 14:15:43 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BRANCH
     *
     * @mbg.generated Wed Apr 17 14:15:43 EEST 2024
     */
    int insert(Branch row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BRANCH
     *
     * @mbg.generated Wed Apr 17 14:15:43 EEST 2024
     */
    Branch selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BRANCH
     *
     * @mbg.generated Wed Apr 17 14:15:43 EEST 2024
     */
    List<Branch> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BRANCH
     *
     * @mbg.generated Wed Apr 17 14:15:43 EEST 2024
     */
    int updateByPrimaryKey(Branch row);
}