package org.rokassirvidas.firstlab.mybatis.dao;

import org.mybatis.cdi.Mapper;
import org.rokassirvidas.firstlab.mybatis.model.Worker;

import java.util.List;
@Mapper
public interface WorkerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKER
     *
     * @mbg.generated Wed Apr 17 14:15:43 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKER
     *
     * @mbg.generated Wed Apr 17 14:15:43 EEST 2024
     */
    int insert(Worker row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKER
     *
     * @mbg.generated Wed Apr 17 14:15:43 EEST 2024
     */
    Worker selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKER
     *
     * @mbg.generated Wed Apr 17 14:15:43 EEST 2024
     */
    List<Worker> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKER
     *
     * @mbg.generated Wed Apr 17 14:15:43 EEST 2024
     */
    int updateByPrimaryKey(Worker row);
}